app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


class Blog(db.Model):
    __tablename__ = 'blogs'

    id = db.Column(db.Integer, primary_key=True)
    blog_title = db.Column(db.String(255))
    blog_post = db.Column(db.String(255))
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def save_blog(self):
        db.session.add(self)
        db.session.commit()
    

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    blog = db.relationship('Blog', backref='user', lazy='dynamic')
    comments = db.relationship('Comment',backref = 'user',lazy = "dynamic")

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))
 
    @property
    def password(self):
        raise AttributeError('You cannnot read the password attribute')

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

# class CommentForm(FlaskForm):
#     category = StringField('Comment Title',validators=[Required()])
#     content = TextAreaField('Comment', validators=[Required()])
#     submit = SubmitField('Submit')

class BlogForm(FlaskForm):
    title = StringField('Blog title',validators=[Required()])
    content = TextAreaField('My Blog')
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    title = StringField('Comment title',validators=[Required()])
    comment = TextAreaField('Blog comment')
    submit = SubmitField('Submit')    

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()
simple = SimpleMDE()

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    # config_options[config_name].init_app(app)

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)   
    login_manager.init_app(app)  
    mail.init_app(app)
    simple.init_app(app)
   
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    
    # setting config
    # from .requests import configure_request
    # configure_request(app)

    # configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,redirect,url_for,abort
from . import main
from . forms import CommentForm,UpdateProfile,BlogForm
from ..models import User,Blog 
from flask_login import login_required, current_user
from .. import db,photos
import markdown2  


# Views
@main.route('/')
def index():
    '''
    function that returns the index page and its data
    '''

    title = 'My Blog'

    return render_template('index.html', title = title)

@main.route('/blog', methods=['GET','POST'])
@login_required
def new_blog():
    form = BlogForm()
    blogs = Blog.query.all()

    if form.validate_on_submit():
        new_blog=Blog(blog_title=form.title.data,blog_post=form.content.data)
        new_blog.save_blog()
        return render_template('blog.html',form=form,blogs=blogs)
    return render_template('blog.html',form=form,blogs=blogs)   

@main.route('/blog/comment/new/<int:id>', methods = ['GET','POST'])
@login_required
def new_comment(id):

    form = CommentForm()

    if form.validate_on_submit():
       
        #updated comment instance
        new_comment = Comment(Blog.id,blog_comment=Comment, user=current_user)

        #save comment method
        new_comment.save_comment()
        return redirect(url_for('.blog',form=form ))

    return render_template('new_comment.html',comment_form=form, blog=blog)

@main.route('/comment/<int:id>')
@login_required

def comment(id):
    comment=Comment.query.get(id)
    if comment is None:
        abort(404)
    format_comment = markdown2.markdown(comment.blog_comment,extras=["code-friendly", "fenced-code-blocks"])
    return render_template('comment.html',comment=comment,format_comment=format_comment)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)    


@main.route('/user/<uname>/update/pic',methods= ['GET', 'POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))    

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}
{% block content %} 
{% endblock %}

app/templates/blog.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class= "col-md-3"> </div>
  <div class="col-md-6">
    <div>
        {{wtf.quick_form(form)}}
        {{simplemde.load}}

        {% for blog in blogs %}
        <ul>
            <p>{{blog.blog_title}}</p>
            <p>{{blog.blog_content}}</p>
            <p>{{blog.posted}}</p>
        </ul>
        {% endfor %}
   </div>
  </div>
  <div class= "col-md-3"> </div>
</div>
</div>
{% endblock %}

app/templates/comment.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content%}
<div class="container-fluid">
  <div class="row">

      {{wtf.quick_form(form)}}
      {{simplemde.load}}

    {% for comment in comment %}
    <div class="col-sm-4">
    <ul>
      <p>{{comment.user}}</p>
      <p>{{comment.blog_id}}</p>
      <p>{{comment.date}}</p>
    </ul>    
    </div>
    {% endfor %}
    <div class="col-sm-8">
      {{format_comment|safe}}
    </div>
  </div>
</div>
{%endblock%}

app/templates/index.html
{% extends 'base.html'%}

<!-- Styles block -->
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <!-- <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/united/bootstrap.min.css" rel="stylesheet" integrity="sha384-+d4wMJSxEP3vzs2qZBElQRTZMXwgWH15Nyn2K/9XjKiHmh3sBuk1Un/IbcdMcYC4" crossorigin="anonymous"> -->
    <link href="https://fonts.googleapis.com/css?family=Itim" rel="stylesheet">

{% endblock %}

{% block content %}
<body style="background-image: url('static/images/purple.webpl')" 
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;>
<div class="container-fluid">
    
<div class="row">

    <div class="col-md-4">

        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="../static/images/1234.png" class="center">
                <div class="card-body">
                  <h5 class="card-title">Sarah Sindet</h5>
                  <p class="card-text">Welcome to 'My Blog'. A place to share ideas, thoughts and advice in this journey called life.</p>
                  <a href="/blog" class="btn btn-primary">New Blog</a>
                  <a href="/comment" class="btn btn-primary">Comment</a>

                </div>
        </div>
    </div>    

    <div class="col-md-4"></div>

    <div class="col-md-4">
        <h2>My Profile</h2>

        <h3>About Me</h3>
        <p>A junior Software Developer.Made way in HTML,CSS ,javascript and flask in python</p>
        
    </div>
                   
    
</div>
</div>
</body>

{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> <img src="../static/images/1.png" width="350"> </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/"></a></li>
        </div>
  
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
          <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
          <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
          {% else %}
          <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
          {%endif%}
        </ul>
  
    </div>
  </div>

app/templates/new_blog.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">       
            {{ wtf.quick_form(blog_form) }}
    </div>

    <div class="col-md-4">
        {{ wtf.quick_form(comment_form) }}
        {{simplemde.load}}
    </div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}

        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}